// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKz5v0M5UhFXpMZrK_xR4VLdGN3rm3SLU',
    appId: '1:897739130442:web:b9366f95d32adf89ba48b3',
    messagingSenderId: '897739130442',
    projectId: 'favoritospix',
    authDomain: 'favoritospix.firebaseapp.com',
    storageBucket: 'favoritospix.appspot.com',
    measurementId: 'G-KHNRS399XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNGG0BZnjZpxgVvapn92mv03IZeCIU_Do',
    appId: '1:897739130442:android:b43b5d88dea27f6fba48b3',
    messagingSenderId: '897739130442',
    projectId: 'favoritospix',
    storageBucket: 'favoritospix.appspot.com',
  );
}
